@startuml AAL-living UseCases

:elderly user: as ElderlyUser

rectangle "AAL" as AAL {
  left to right direction

ElderlyUser ---> (Add a reminder)
ElderlyUser ---> (Notify reminder)
ElderlyUser ---> (Get all reminders)
ElderlyUser ---> (Delete Reminder)
ElderlyUser ---> (Add medication)
ElderlyUser --> (Notify medication)
ElderlyUser --> (Get All Medications)
ElderlyUser --> (Delete Medication)
ElderlyUser ---> (Call emergency contact)
ElderlyUser ---> (Send message)
ElderlyUser ---> (activate panic button)
ElderlyUser --> (change user details)
ElderlyUser --> (Toggle Notifications)
ElderlyUser ----> (Toggle accessibility tools)
ElderlyUser --> (change emergency contact)
ElderlyUser ---> (Get users current Fitbit activity)
}

rectangle "Twilio" as TwilioAPI
rectangle "FitbitAPI" as FitbitAPI
database "SQLite" as DB
rectangle "socket.io" as SocketIO
rectangle "localStorage" as localStorage

(activate panic button) -- TwilioAPI
(Call emergency contact) -- TwilioAPI
(Get users current Fitbit activity) -- FitbitAPI

(Add a reminder) -- DB
(Get all reminders) -- DB
(Delete Reminder) -- DB
(change emergency contact) -- localStorage
(Toggle accessibility tools) -- localStorage
(change user details) -- DB

(Add medication) -- DB
(Delete Medication) -- DB
(Get All Medications) -- DB

(Send message) -- SocketIO


@enduml
