@startuml AAL-living UseCases

:elderly user: as ElderlyUser

rectangle "AAL" as AAL {
  left to right direction

ElderlyUser ----> (Add a reminder)
ElderlyUser ---> (Notify reminder)
ElderlyUser ---> (Delete Reminder)
ElderlyUser ---> (Add medication)
ElderlyUser --> (Notify medication)
ElderlyUser --> (Delete Medication)
ElderlyUser ---> (Send message)
ElderlyUser ---> (activate panic button)
ElderlyUser --> (change profile)
ElderlyUser --> (Toggle Notifications)
ElderlyUser ---> (Toggle accessibility tools)
ElderlyUser ---> (change emergency contact)
ElderlyUser ----> (Get users current Fitbit activity)
}

rectangle "Twilio" as TwilioAPI
rectangle "FitbitAPI" as FitbitAPI
database "SQLite" as DB
rectangle "socket.io" as SocketIO
rectangle "localStorage" as localStorage
rectangle "webKit" as webKit
rectangle "notification" as notification

(activate panic button) <--> TwilioAPI
(Get users current Fitbit activity) <--> FitbitAPI

(Add a reminder) -- DB
(Delete Reminder) -- DB
(change emergency contact) -- localStorage
(Toggle accessibility tools) -- localStorage
(Toggle accessibility tools) -- webKit
(change profile) -- DB
(Toggle Notifications) --- notification
(Notify reminder) --- notification
(Notify medication) --- notification

(Add medication) -- DB
(Delete Medication) -- DB

(Send message) -- SocketIO


@enduml
